var mqtt = require('mqtt');
var client  = mqtt.connect('tcp://localhost:1883');
var delay = require('delay');
// var client = mqtt.connect('mqtt://test.mosquitto.org');

let packet = [
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },{
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },{
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },{
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480521",
        "speed": 20,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480522",
        "speed": 21,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 38,
        "tirePressureRF": 36,
        "tirePressureLR": 37,
        "tirePressureRR": 34,
        "status": {},
        "acceleration": "[0.1,0,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480523",
        "speed": 22,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 35,
        "tirePressureLR": 38,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0.2,0.1,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480524",
        "speed": 22,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 33,
        "tirePressureRF": 36,
        "tirePressureLR": 39,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0.2,0.2,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480525",
        "speed": 23,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 32,
        "tirePressureLR": 40,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0.3,0.2,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480526",
        "speed": 25,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 38,
        "tirePressureRF": 40,
        "tirePressureLR": 32,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0.4,0.1,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480527",
        "speed": 28,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 41,
        "tirePressureLR": 35,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0.5,0.2,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480528",
        "speed": 30,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 38,
        "tirePressureLR": 37,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0.6,0.1,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480529",
        "speed": 32,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 42,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0.6,0.3,0]",
        "note": "",
    },
    {
        "vin": "aji0922",
        "longitude": "24.25",
        "latitude": "124.25",
        "deviceId": "d001",
        "timestamp": "1622480530",
        "speed": 14,
        "acceleratorPos": 10,
        "breakingPos": 10,
        "PRNDL": "P",
        "travelDirection": "",
        "steeringWheelPos": 20,
        "tirePressureLF": 36,
        "tirePressureRF": 36,
        "tirePressureLR": 36,
        "tirePressureRR": 36,
        "status": {},
        "acceleration": "[0.1,0,0]",
        "note": "",
    }
]


client.on('connect', async function () {
    for(var i=0;i<packet.length;i++){
        client.publish('bedr/vid', JSON.stringify(packet[i]), { qos: 1});
        console.log('publish:', i+1);
        await delay(1000);
    }
    console.log('car crash');
    client.end();
});
